apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clear-sessions
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0
      template:
        spec:
          containers:
          - name: django-clear-sessions
            image: redbor24/django_app:latest
            imagePullPolicy: IfNotPresent
            command:
              - python
              - manage.py
              - clearsessions
          restartPolicy: OnFailure
          envFrom:
            - configMapRef:
                name: django-config
