apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    name: django-migrate
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: django-migrate
          image: redbor24/django_app:latest
          imagePullPolicy: IfNotPresent
          command:
            - python
            - manage.py
            - migrate
            - --noinput
          envFrom:
          - secretRef:
              name: django-secret
