apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: default
type: Opaque
stringData:
  SECRET_KEY: django-insecure-0if40nf4nf93n4
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
