apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: default
type: Opaque
stringData:
  SECRET_KEY: <DJANGO-SECRET_KEY>  # Впишите свой ключ Django
  DATABASE_URL: <postgres://user:password@host:port/db_name>  # Впишите пользователя, пароль, хост и имя БД
